apiVersion: v1
kind: Pod
metadata:
  name: toleration2
  labels:
    purpose: "toleration-demo"
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"