apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
  labels:
    purpose: "anti-affinity"
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu         
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"